### ISSUE TITLE
Mail subscribe submission missing 'https://'

### ISSUE THREAD

**Issue by sindarina** [zincmade/apprenticeship.community#18]
The '//...' URL works great for mixed content sites, but for this I'd be sure it uses HTTPS, and specify the 'scheme' explicitly. So instead of; '//zincma.us10.list-manage.com/', you should be able to use 'https://zincma.us10.list-manage.com/' instead.

Always a good idea for external URLs, basically :-)

**Comment by zspencer** [comment]
:+1: Thanks a ton! I've also created #19, which I'll try to figure out next weekend.
