### ISSUE TITLE
UglifyJS required for local javascript

### ISSUE THREAD

**Issue by dominic** [zincmade/apprenticeship.community#24]
The `js` process in the Procfile requires UglifyJS to be installed on the user's system via the `build-js` make target:

```
js: bin/rerun -x -d "site/assets/src-js" make build-js
```

Not sure if there's a Jekyll-y way to do this (doesn't seem like it? :frowning:)

**Comment by zspencer** [comment]
Hmmm, is there a ruby equivalent? Or should I make npm a dependency?

**Comment by dominic** [comment]
Switching to something like http://ixti.net/jekyll-assets/ might be the way to go.

**Comment by zspencer** [comment]
@dominic that looks super! I'd love to see a PR :purple_heart:

**Comment by dominic** [comment]
Ask and ye shall receive https://github.com/zincmade/apprenticeship.community/pull/27
