### ISSUE TITLE
One-time sponsorship button

### ISSUE THREAD

**Issue by kmanion** [zincmade/apprenticeship.community#54]
A community member asked if they could make a one-time monetary contribution to the community. (vs. a recurring payment on Patreon) I do see that Patreon supports one-time contributions, but the patron has to delete their pledge, and that seems less practical, considering Patreon takes some fees.

I thought we could create a one-time sponsorship button for those who would prefer to make one-off contributions. thoughts, @zspencer ?

**Comment by zspencer** [comment]
It should be possible. I intend to re-work the membership flow to be using our own code instead of typeform; but that would require me to get SSL working on the page; which I've delayed til I get back from India.

It may also be possible that Stripe just supports this out of the box; or something like MoonClerk could work.

**Comment by ChaeOkay** [comment]
Found a pleasant UI/UX for doing what's described here. They are using Paypal instead of Strip, but, just wanted to share their lovely form.

http://devchat.tv/donate

**Comment by zspencer** [comment]
@ChaeOkay I like that as well. Does it work with static sites?

**Comment by ChaeOkay** [comment]
@zspencer I really have no idea how they implemented it, but, Stripe seems to have an embedded form out of the box https://stripe.com/docs/tutorials/checkout

This was more of a design suggestion!

**Comment by ChaeOkay** [comment]
So, I guess the answer to you question is I don't know, but it seems likely!

**Comment by ChaeOkay** [comment]
Eh...
https://json.expert/a-free-self-hosted-backend-for-stripe-checkout/

**Comment by ChaeOkay** [comment]
Modifying response to no :(

**Comment by ChaeOkay** [comment]
Ha! I found this issue again through https://www.os4w.org . @zspencer any thoughts on trying [Snipcart](https://snipcart.com/developers)?

I'm not sure how the transition out of Patreon would go, but the holidays are coming up...

**Comment by zspencer** [comment]
@ChaeOkay Ah, hmmm... I'm not really sure if it makes sense to work on this right now seeing as we've been pretty low-energy for the past few months and I'd feel bad working towards monetization :(

**Comment by ChaeOkay** [comment]
:+1:
